Add Python bindings (#76)
* Drop all 'dynamic_*' libraries

* Reorganize headers and subdirs, add namespaced CMake targets

Moved all headers under a single include/novatel_edie directory at the repo root.

Split decoders/common into common/ and decoders/common to avoid a circular dependency between stream_interface and decoders/common.

Renamed:
- hw_interface/stream_interface -> stream_interface
- decoders/novatel -> decoders/oem

Added an edie_ prefix to all output names of libraries to avoid potential conflicts with other projects.

* Copy dependency shared libs to ${OUTPUT_DIR} on all platforms

* common_test does not require TEST_DATABASE_PATH

* Fix a typo

* CI: inspect build/out/bin dir

* Set RPATH to $ORIGIN for the copied third-party libs

* set CMAKE_CXX_STANDARD

* Add an aggregate novatel_edie::novatel_edie target

* Add Conan packaging support, support system deps, refactor CMake

* Add SetDefaultProfile.cmake

* conan_provider.cmake: fix missing runtime type detection for ClangCL

* Fix stream_interface folder name

* novatel_test -> oem_test

* CI: Add include/ to clang-format and editorconfig steps

* Copy shared libs only when building executables

* conanfile.py: set spdlog version to force=True

To work around the spdlog version conflict from gegles-spdlog_setup

* Make asciiFieldMap and jsonFieldMap non-static

The BaseEncoder static fields are not visible to the Encoder class in another shared library. Only works when linking statically.

Has no measurable impact on performance based on the test suite.

* Require Conan v2.4.0 or newer for CONAN_RUNTIME_LIB_DIRS

https://github.com/conan-io/conan/commit/29315889b45f24f83c6530a8bdb18b4c547e1cba

* Fix u32string formatting in exceptions

* range_cmp_test.cpp: update decoded message values

And improve the equality asserts to display the mismatching string contents on failure.

* RangeDecompressor: switch from float to double in calculations

Single precision is not sufficient to guarantee stable numerical values in the decoded output to the 8th decimal position output by the ASCII messages.

Also improve the equality asserts to display the mismatching string contents on failure.

* Restore Python dir

* Update Python package setup, use pyproject.toml

* Clean up the Python libs a bit

* Set up project skeleton for nanobind + cibuildwheel

* Disable some nanobind warnings

* Add Python bindings for hw_interface

* Rename hw_interface -> stream_interface

* Translate C++ examples to Python, WIP

* Add Python bindings for decoders, WIP

* Add support for loggers

* Add bindings for all decoder classes

* Convert STATUS error statuses into exceptions

* Add InputFileStream

* Translate Python examples, WIP

* Improve MessageDecoder output structure

* Translate C++ unit tests to Python, WIP

* Translate all hw_interface tests to Python

* Convert test_framer.py, split into separate files

* Convert test_command_encode.py

* Fix test_decode_encode.py syntax errors

* Fix test_benchmark.py syntax errors

* Fix test_fileparser.py syntax errors

* Convert test_filter.py

* Convert test_rangecmp.py

* Convert test_rxconfig.py

* Convert test_decode_encode.py

* Convert test_novatel_types.py

* Cover jsonreader.hpp with bindings

* Add bindings for IntermediateMessage and its fields

* Fix nb::cast() error by not storing a pointer

* Nicer enum formatting

* Add __repr__ for main structs

* Fix Encoder.encode()

* Rename IntermediateHeader and IntermediateMessage to just Header and Message in bindings

* Fix test_decode_encode.py

* Better repr-s for jsonreader.cpp types

* Convert test_novatel_types.py

* Fix FIELD_ARRAY type bindings

* Add Python 3.8 support to database_to_html.py

* Fixes

* All green in test_decode_encode.py

* Use bytes() for Commander API

* Fix test_fileparser.py

* Add bindings for NExcept

* Move Python tests to subdirs

* Always run tests inside a temp dir

* Use importlib.resources to access the default JSON DB

* Fix resource paths in test_framer.py

* Use a JsonReader singleton by default for all decoder classes in Python

* Update examples

* Add STATUS.raise_on_error() convenience method

* Clean up converter_components.py

* Use argparse in examples, merge json_parser.py and converter_parser.py

* Drop _binding from the Python module names

* Fix broken hex literal formatting in test_decode_encode.py

* Update test_novatel_types.py

* Add comments for message_decoder.cpp

* Fix test_novatel_types.py constants

* Improve BaseField and related repr

* Tweak converter_components.py

* Use min_json_db in test_novatel_types.py

* Fix logger tests

* Add get_default_database() function

* Better header repr info, add get_msg_def()

* Rename Logger -> Logging in Python

Too visually similar with the SpdLogLogger instances that are usually named "logger" as well.

* Use status.raise_on_error() in tests

* Add rv policies for pointer return values in bindings

* test_novatel_types.py: mark two broken tests as xfail

* Add support for remaining tests in test_rangecmp.py

* Mark the two failing tests in test_rangecmp.py as xfail

* Add support for remaining test in test_multioutputfilestream.py

* Fix FileParser constructor bindings

* Add .message_fields and .message_description to MetaData

* Remove debug prints

* Fix CONVERSION_TO_FLAT_BIN_BESTSATS_ASC_AND_BIN test

* Enable some RANGECMP tests, update their expected decoded messages

* Full test coverage of test_multioutputfilestream.py

* Finish the conversion of all Python examples

* Increase buffer size when encoding into JSON

* Update test_fileparser.py a bit

* Convert pointers in the public API to std::shared_pointer

* Mark the two failing type tests as skip, not just xfail

In addition to failing, they also cause a reference cycle somewhere and leak memory, triggering nanobind to print a loud warning on interpreter shutdown.

* Merge bindings to fix macOS x86_64 issues

Tests for x86_64 on macOS failed in some cases when hw_interface bindings were being used in decoders method bindings.

* Fix _snprintf issue on Windows for bindings

* Reorganize header structure to be more consistent

* converter_parser.py: fix typo

* Tweak PyIntermediateMessage formatting

* Add .to_dict() to PyIntermediateMessage

* Convert PyIntermediateMessage values only when requested

* Add __len__ to PyIntermediateMessage

* Use normal Python file handles as input in examples

* Streamline converter_components.py a bit

* Use atexit.register(Logging.shutdown) in examples

* Streamline converter_components.py a bit more

* Improve frame formatting in converter_components.py

* Drop FIELD_CONTAINER_ERROR_ON_COPY test

* Tidy python/CMakeLists.txt

* pytest: fixes, add test_get_default_database

* Merge test_framer.py changes from novatel_test.cpp

* Merge test_decode_encode.py changes from novatel_test.cpp

* Merge test_command_encode.py changes from novatel_test.cpp

* Merge test_filter.py changes from novatel_test.cpp

* Merge test_file_parser.py changes from novatel_test.cpp

* Update test_novatel_types.py

* All Python tests are green again

* Rename Python tests novatel -> oem

* Fix test_novatel_types.py

* Fix a memory leak in std::u32string nanobind caster

* Explicitly cast to std::u32string_view in stream_interface bindings

Otherwise fails with a runtime error.

* json_reader.hpp: use a switch

* Update test_novatel_types.py

* Make clang-tidy-18 happy

* CI: Add Python build pipeline

* Set build-profile cppstd to 17 for patchelf

* Tweak Conan auto build profile for macOS

* Install patchelf on macOS as well

* Fix minor typos

* Drop python/doc, which has not been tested

* Drop python/readme.md

* Apply clang-tidy suggestions for Python bindings

* Update Python bindings version

* Include the main metadata info in the decoded messages

* Include message_crc in PyDecodedMessage as well

* Make Metadata input to HeaderDecoder bindings optional

* Drop stream_interface from Python bindings

* file_parser.hpp: replace ifstream with a more general istream

* file_parser.hpp: replace std::istream* with shared_ptr

* Add Python<->C++ stream wrapper for FileParser

* Apply clang-format, use <iosfwd> instead of <iostream>

* Bump minimal nanobind version

* Move Python tests

* Add JSON DB enums as IntEnums under novatel_edie.message_enums.*

* Cast decoded enum values to appropriate IntEnum type

* clang-format

* Add iterator support to FileParser bindings

* Update Python examples

* Rename build.yml -> cpp.yml

* Fix decoding of %c (used in BESTUTM)

Was always being decoded as 0.

* Rename message_enums -> enums

* Flatten Python bindings source dir

* Refactor JsonReader into MessageDatabase and JsonDbReader classes

Also replaced all std::u32string paths with a std::filesystem::path that natively supports Unicode strings.

* Add a PyMessageDatabase wrapper to bindings

* Keep track of the DB a message was derived from

* Add .enums dictionary to MessageDatabase

* Use a move constructor for the MessageDatabase -> PyMessageDatabase conversion.

* Fix spdlog_setup::from_file() not accepting fs::path

* Fix -Wpessimizing-move warning

* Lower-case test names to match PEP8 conventions

* Add iterator support to Parser bindings

* Add tests for Parser

* Set NB_DOMAIN to avoid any conflicts with other bindings

* Limit fmt to 11.0.2 for compatibility with spdlog

error: ‘template<class T, class ... Args> fmt::v11::basic_string_view<Char> spdlog::details::to_string_view’ redeclared as different kind of entity
  369 | inline fmt::basic_string_view<T> to_string_view(fmt::basic_format_string<T, Args...> fmt) {

* Fix a fatal warning on MSVC

* CI: set editorconfig-checker version

To fix "Error: The binary 'ec-linux-amd64*' not found".

* ThirdParty.cmake: don't find PATCHELF_EXECUTABLE on macOS

* Don't build x86 Python wheels

Conan packages have a tool_requires on CMake, but it's not available for x86.

Could also possibly tweak the build scripts to work around this.

* Revert "CI: set editorconfig-checker version"

This reverts commit 66900fd1b4a883c11824dfe1de14f5ab1fd67c66.